kind: pipeline
type: docker
name: default
steps:
  - name: backend
    image: python:3.12
    environment:
      JWT_SECRET:
        from_secret: JWT_SECRET
      SMTP_SERVER:
        from_secret: SMTP_SERVER
      SMTP_PORT:
        from_secret: SMTP_PORT
      SMTP_SENDER:
        from_secret: SMTP_SENDER
      SMTP_PASSWORD:
        from_secret: SMTP_PASSWORD
      MONGO_PORT:
        from_secret: MONGO_PORT
      MONGO_HOST:
        from_secret: MONGO_HOST
      MONGO_PASSWORD:
        from_secret: MONGO_PASSWORD
      MONGO_USER:
        from_secret: MONGO_USER
    commands:
      - cd backend
      - pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
      - python main.py
trigger:
  branch:
    - master
  event:
    - push