kind: pipeline
type: docker
name: default

steps:
  - name: seiun_sodou # Nuxt Build
    image: node:20
    environment:
      JWT_SECRET:
        from_secret: JWT_SECRET
      SMTP_SERVER:
        from_secret: SMTP_SERVER
      SMTP_PORT:
        from_secret: SMTP_PORT
      SMTP_SENDER:
        from_secret: SMTP_SENDER
      SMTP_PASSWORD:
        from_secret: SMTP_PASSWORD
      MONGO_HOST:
        from_secret: MONGO_HOST
      MONGO_PORT:
        from_secret: MONGO_PORT
      MONGO_USER:
        from_secret: MONGO_USER
      MONGO_PASSWORD:
        from_secret: MONGO_PASSWORD
      S3_ACCESS_KEY_ID:
        from_secret: S3_ACCESS_KEY_ID
      S3_SECRET_ACCESS_KEY:
        from_secret: S3_SECRET_ACCESS_KEY
      S3_ENDPOINT:
        from_secret: S3_ENDPOINT
      S3_BUCKET:
        from_secret: S3_BUCKET
      ZHIPU_TOKEN:
        from_secret: ZHIPU_TOKEN
    commands:
      - export NODE_OPTIONS="--max-old-space-size=4096"
      - export JWT_SECRET=$JWT_SECRET
      - export SMTP_SERVER=$SMTP_SERVER
      - export SMTP_PORT=$SMTP_PORT
      - export SMTP_SENDER=$SMTP_SENDER
      - export SMTP_PASSWORD=$SMTP_PASSWORD
      - export MONGO_HOST=$MONGO_HOST
      - export MONGO_PORT=$MONGO_PORT
      - export MONGO_USER=$MONGO_USER
      - export MONGO_PASSWORD=$MONGO_PASSWORD
      - export S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
      - export S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
      - export S3_ENDPOINT=$S3_ENDPOINT
      - export S3_BUCKET=$S3_BUCKET
      - export ZHIPU_TOKEN=$ZHIPU_TOKEN
      - npm i -g pnpm --registry=https://registry.npmmirror.com
      - pnpm config set registry https://registry.npmmirror.com
      - pnpm i
      - pnpm run build
      - rm -rf /opt/seiun_sodou/*
      - mkdir -p /opt/seiun_sodou/
      - cp -r ./* ./.??* /opt/seiun_sodou/
    volumes:
      - name: build_volume
        path: /opt/seiun_sodou/

volumes:
  - name: build_volume
    host:
      path: /opt/seiun_sodou/

trigger:
  branch:
    - master
  event:
    - push
    - custom
