services:
  seiunsodou:
    image: ghcr.io/mejiro-ardan/seiunsodou/seiunsodou:latest
    container_name: seiunsodou
    environment:
      - TZ=Asia/Shanghai
      - JWT_SECRET =  "" # JWT密钥，必填
      - SMTP_SERVER = "" # SMTP服务器，默认启用starttls
      - SMTP_PORT = "" # SMTP端口
      - SMTP_SENDER = "" # SMTP发送
      - SMTP_PASSWORD = "" # SMTP密码
      - MONGO_PORT = "" # MongoDB端口
      - MONGO_HOST = "" # MongoDB主机
      - MONGO_PASSWORD = "" # MongoDB密码
      - MONGO_USER = "" # MongoDB用户
    ports:
      - "3000:3000"
    networks:
      - seiunsodou-network
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongo:6.0.16
    volumes:
      - ./data/db:/data/db
    networks:
      - seiunsodou-network
    restart: unless-stopped

networks:
  seiunsodou-network:
    driver: bridge
